When I do cross tab messaging, I get this error on the tab that receives the usermessage: Uncaught (in promise) TypeError: e.replace is not a function at a.Converter.makeHtml (showdown.js:2459:17) at handleincoming_message (57a18b57-b0bc-437f-a1a6-87edc37d4614:697:58) at 57a18b57-b0bc-437f-a1a6-87edc37d4614:673:29 the handle_incoming_message should be being called with a valid message object, can you find how it's being misused?